version: '3'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: your_database
      MYSQL_USER: your_username
      MYSQL_PASSWORD: your_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    networks:
      - mynetwork
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  nodeapp:
    build: .
    depends_on:
      - mysql
    ports:
      - "3000:3000"
    networks:
      - mynetwork

networks:
  mynetwork:
