version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: your_database
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"
    networks:
      - mynetwork
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  nodeapp:
    build: .
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    networks:
      - mynetwork

networks:
  mynetwork:
